q1=input('first question:')
q2=input('second question:')
q3=input('third question:')
q4=input('fourth question:')
print('question used given below:----')
print('1)this is default first question',q1)
print('2)this is default second question',q2)
print('3)this is default third question',q3)
print('4)this is default fourth question',q4)